Repository prgrms-be-devcourse/NBB1_1_3_Team03, pull requests merged in 2024-11, with the labels that each got.

#3 Migration/1 product
  build.gradle
  build.gradle.kts
  settings.gradle
  src/main/java/com/sscanner/team/products/controller/ProductController.java
  src/main/java/com/sscanner/team/products/controller/ProductController.kt
  src/main/java/com/sscanner/team/products/entity/Product.java
  src/main/java/com/sscanner/team/products/entity/Product.kt
  src/main/java/com/sscanner/team/products/entity/ProductImg.java
  src/main/java/com/sscanner/team/products/entity/ProductImg.kt
  src/main/java/com/sscanner/team/products/repository/ProductImgRepository.java
  src/main/java/com/sscanner/team/products/repository/ProductImgRepository.kt
  src/main/java/com/sscanner/team/products/repository/ProductRepository.java
  src/main/java/com/sscanner/team/products/repository/ProductRepository.kt
  src/main/java/com/sscanner/team/products/responsedto/ProductImgResponseDto.java
  src/main/java/com/sscanner/team/products/responsedto/ProductImgResponseDto.kt
  src/main/java/com/sscanner/team/products/responsedto/ProductWithImgResponseDto.java
  src/main/java/com/sscanner/team/products/responsedto/ProductWithImgResponseDto.kt
  src/main/java/com/sscanner/team/products/service/ProductImgService.java
  src/main/java/com/sscanner/team/products/service/ProductImgService.kt
  src/main/java/com/sscanner/team/products/service/ProductImgServiceImpl.java
  src/main/java/com/sscanner/team/products/service/ProductImgServiceImpl.kt
  src/main/java/com/sscanner/team/products/service/ProductService.java
  src/main/java/com/sscanner/team/products/service/ProductService.kt
  src/main/java/com/sscanner/team/products/service/ProductServiceImpl.java
  src/main/java/com/sscanner/team/products/service/ProductServiceImpl.kt
Labels: 정원, Migration

#9 Migration/4 point
  src/main/java/com/sscanner/team/points/common/PointConstants.java
  src/main/java/com/sscanner/team/points/common/PointConstants.kt
  src/main/java/com/sscanner/team/points/config/RedisConfig.java
  src/main/java/com/sscanner/team/points/config/RedisConfig.kt
  src/main/java/com/sscanner/team/points/config/TaskExecutorConfig.java
  src/main/java/com/sscanner/team/points/config/TaskExecutorConfig.kt
  src/main/java/com/sscanner/team/points/controller/PointController.java
  src/main/java/com/sscanner/team/points/controller/PointController.kt
  src/main/java/com/sscanner/team/points/dto/PointUpdateDto.java
  src/main/java/com/sscanner/team/points/dto/PointUpdateDto.kt
  src/main/java/com/sscanner/team/points/dto/requestdto/PointRequestDto.java
  src/main/java/com/sscanner/team/points/dto/requestdto/PointRequestDto.kt
  src/main/java/com/sscanner/team/points/dto/responsedto/PointWithUserIdResponseDto.java
  src/main/java/com/sscanner/team/points/dto/responsedto/PointWithUserIdResponseDto.kt
  src/main/java/com/sscanner/team/points/entity/UserPoint.java
  src/main/java/com/sscanner/team/points/entity/UserPoint.kt
  src/main/java/com/sscanner/team/points/redis/PointRedisService.java
  src/main/java/com/sscanner/team/points/redis/PointRedisService.kt
  src/main/java/com/sscanner/team/points/redis/PointRedisServiceImpl.java
  src/main/java/com/sscanner/team/points/redis/PointRedisServiceImpl.kt
  src/main/java/com/sscanner/team/points/redis/RedisDataInitializer.java
  src/main/java/com/sscanner/team/points/redis/RedisDataInitializer.kt
  src/main/java/com/sscanner/team/points/repository/PointRepository.java
  src/main/java/com/sscanner/team/points/repository/PointRepository.kt
  src/main/java/com/sscanner/team/points/scheduler/PointScheduler.java
  src/main/java/com/sscanner/team/points/scheduler/PointScheduler.kt
  src/main/java/com/sscanner/team/points/service/PointBackupService.java
  src/main/java/com/sscanner/team/points/service/PointBackupService.kt
  src/main/java/com/sscanner/team/points/service/PointBackupServiceImpl.java
  src/main/java/com/sscanner/team/points/service/PointBackupServiceImpl.kt
  src/main/java/com/sscanner/team/points/service/PointService.java
  src/main/java/com/sscanner/team/points/service/PointService.kt
  src/main/java/com/sscanner/team/points/service/PointServiceImpl.java
  src/main/java/com/sscanner/team/points/service/PointServiceImpl.kt
  src/main/java/com/sscanner/team/user/entity/User.java
Labels: 정원, Migration

#11 Migration/10 payment
  src/main/java/com/sscanner/team/barcode/entity/Barcode.java
  src/main/java/com/sscanner/team/payment/controller/PaymentController.java
  src/main/java/com/sscanner/team/payment/controller/PaymentController.kt
  src/main/java/com/sscanner/team/payment/entity/PaymentRecord.java
  src/main/java/com/sscanner/team/payment/entity/PaymentRecord.kt
  src/main/java/com/sscanner/team/payment/repository/PaymentRepository.java
  src/main/java/com/sscanner/team/payment/repository/PaymentRepository.kt
  src/main/java/com/sscanner/team/payment/requestdto/PointPaymentRequestDto.java
  src/main/java/com/sscanner/team/payment/requestdto/PointPaymentRequestDto.kt
  src/main/java/com/sscanner/team/payment/responsedto/PointPaymentResponseDto.java
  src/main/java/com/sscanner/team/payment/responsedto/PointPaymentResponseDto.kt
  src/main/java/com/sscanner/team/payment/service/PaymentService.java
  src/main/java/com/sscanner/team/payment/service/PaymentService.kt
  src/main/java/com/sscanner/team/payment/service/PaymentServiceImpl.java
  src/main/java/com/sscanner/team/payment/service/PaymentServiceImpl.kt
  src/main/java/com/sscanner/team/products/entity/Product.kt
  src/main/java/com/sscanner/team/user/entity/User.java
Labels: 정원, Migration

#12 Migration/7 sms
  src/main/java/com/sscanner/team/sms/controller/SmsController.java
  src/main/java/com/sscanner/team/sms/controller/SmsController.kt
  src/main/java/com/sscanner/team/sms/repository/SmsRepository.java
  src/main/java/com/sscanner/team/sms/repository/SmsRepository.kt
  src/main/java/com/sscanner/team/sms/requestdto/SmsRequestDto.java
  src/main/java/com/sscanner/team/sms/requestdto/SmsRequestDto.kt
  src/main/java/com/sscanner/team/sms/requestdto/SmsVerifyRequestDto.java
  src/main/java/com/sscanner/team/sms/requestdto/SmsVerifyRequestDto.kt
  src/main/java/com/sscanner/team/sms/service/SmsService.java
  src/main/java/com/sscanner/team/sms/service/SmsService.kt
  src/main/java/com/sscanner/team/sms/service/SmsServiceImpl.java
  src/main/java/com/sscanner/team/sms/service/SmsServiceImpl.kt
  src/main/java/com/sscanner/team/sms/util/SmsCertificationUtil.java
  src/main/java/com/sscanner/team/sms/util/SmsCertificationUtil.kt
Labels: 지은, Migration

#16 Migration/13 login-logout-join
  src/main/java/com/sscanner/team/auth/constant/JwtConstants.java
  src/main/java/com/sscanner/team/auth/constant/JwtConstants.kt
  src/main/java/com/sscanner/team/auth/jwt/CustomLogoutFilter.java
  src/main/java/com/sscanner/team/auth/jwt/CustomLogoutFilter.kt
  src/main/java/com/sscanner/team/auth/jwt/JWTFilter.java
  src/main/java/com/sscanner/team/auth/jwt/JWTFilter.kt
  src/main/java/com/sscanner/team/auth/jwt/JWTUtil.java
  src/main/java/com/sscanner/team/auth/jwt/JWTUtil.kt
  src/main/java/com/sscanner/team/auth/jwt/LoginFilter.java
  src/main/java/com/sscanner/team/auth/jwt/LoginFilter.kt
  src/main/java/com/sscanner/team/auth/service/CustomUserDetailsService.java
  src/main/java/com/sscanner/team/auth/service/CustomUserDetailsService.kt
  src/main/java/com/sscanner/team/auth/service/UserDetailsImpl.kt
  src/main/java/com/sscanner/team/global/configure/SecurityConfig.java
  src/main/java/com/sscanner/team/global/configure/SecurityConfig.kt
  src/main/java/com/sscanner/team/user/entity/User.java
  src/main/java/com/sscanner/team/user/entity/User.kt
  src/main/java/com/sscanner/team/user/requestdto/UserJoinRequestDto.java
  src/main/java/com/sscanner/team/user/requestdto/UserJoinRequestDto.kt
  src/main/java/com/sscanner/team/user/requestdto/UserLoginRequestDto.java
  src/main/java/com/sscanner/team/user/requestdto/UserLoginRequestDto.kt
  src/main/java/com/sscanner/team/user/responsedto/UserDetailsImpl.java
  src/main/java/com/sscanner/team/user/responsedto/UserJoinResponseDto.java
  src/main/java/com/sscanner/team/user/responsedto/UserJoinResponseDto.kt
  src/main/java/com/sscanner/team/user/service/UserService.java
  src/main/java/com/sscanner/team/user/service/UserService.kt
  src/main/java/com/sscanner/team/user/service/UserServiceImpl.java
  src/main/java/com/sscanner/team/user/service/UserServiceImpl.kt
Labels: 지은, Migration

#15 Migration/14 gifticon barcode
  src/main/java/com/sscanner/team/barcode/common/BarcodeConstants.java
  src/main/java/com/sscanner/team/barcode/common/BarcodeConstants.kt
  src/main/java/com/sscanner/team/barcode/controller/BarcodeController.java
  src/main/java/com/sscanner/team/barcode/controller/BarcodeController.kt
  src/main/java/com/sscanner/team/barcode/entity/Barcode.java
  src/main/java/com/sscanner/team/barcode/entity/Barcode.kt
  src/main/java/com/sscanner/team/barcode/repository/BarcodeRepository.java
  src/main/java/com/sscanner/team/barcode/repository/BarcodeRepository.kt
  src/main/java/com/sscanner/team/barcode/responsedto/BarcodeResponseDto.java
  src/main/java/com/sscanner/team/barcode/responsedto/BarcodeResponseDto.kt
  src/main/java/com/sscanner/team/barcode/service/BarcodeGenerator.java
  src/main/java/com/sscanner/team/barcode/service/BarcodeGenerator.kt
  src/main/java/com/sscanner/team/barcode/service/BarcodeService.java
  src/main/java/com/sscanner/team/barcode/service/BarcodeService.kt
  src/main/java/com/sscanner/team/barcode/service/BarcodeServiceImpl.java
  src/main/java/com/sscanner/team/barcode/service/BarcodeServiceImpl.kt
  src/main/java/com/sscanner/team/gifticon/controller/GifticonController.java
  src/main/java/com/sscanner/team/gifticon/controller/GifticonController.kt
  src/main/java/com/sscanner/team/gifticon/responsedto/GifticonResponseDto.java
  src/main/java/com/sscanner/team/gifticon/responsedto/GifticonResponseDto.kt
  src/main/java/com/sscanner/team/gifticon/service/GifticonService.java
  src/main/java/com/sscanner/team/gifticon/service/GifticonService.kt
Labels: 정원, Migration

#20 Migration/19 reissue
  src/main/java/com/sscanner/team/auth/controller/ReissueController.java
  src/main/java/com/sscanner/team/auth/controller/ReissueController.kt
  src/main/java/com/sscanner/team/auth/repository/RedisRefreshTokenRepository.java
  src/main/java/com/sscanner/team/auth/repository/RedisRefreshTokenRepository.kt
  src/main/java/com/sscanner/team/auth/responsedto/RefreshResponseDto.kt
  src/main/java/com/sscanner/team/auth/service/ReissueService.java
  src/main/java/com/sscanner/team/auth/service/ReissueService.kt
  src/main/java/com/sscanner/team/auth/service/ReissueServiceImpl.java
  src/main/java/com/sscanner/team/auth/service/ReissueServiceImpl.kt
  src/main/java/com/sscanner/team/user/entity/User.java
  src/main/java/com/sscanner/team/user/responsedto/RefreshResponseDto.java
Labels: 지은, Migration

#22 Migration/21 user
  src/main/java/com/sscanner/team/global/utils/UserUtils.java
  src/main/java/com/sscanner/team/global/utils/UserUtils.kt
  src/main/java/com/sscanner/team/user/controller/UserController.java
  src/main/java/com/sscanner/team/user/controller/UserController.kt
  src/main/java/com/sscanner/team/user/repository/UserRepository.java
  src/main/java/com/sscanner/team/user/repository/UserRepository.kt
  src/main/java/com/sscanner/team/user/requestdto/UserFindIdRequestDto.java
  src/main/java/com/sscanner/team/user/requestdto/UserFindIdRequestDto.kt
  src/main/java/com/sscanner/team/user/requestdto/UserNicknameUpdateRequestDto.java
  src/main/java/com/sscanner/team/user/requestdto/UserNicknameUpdateRequestDto.kt
  src/main/java/com/sscanner/team/user/requestdto/UserPasswordChangeRequestDto.java
  src/main/java/com/sscanner/team/user/requestdto/UserPasswordChangeRequestDto.kt
  src/main/java/com/sscanner/team/user/requestdto/UserPhoneUpdateRequestDto.java
  src/main/java/com/sscanner/team/user/requestdto/UserPhoneUpdateRequestDto.kt
  src/main/java/com/sscanner/team/user/requestdto/UserResetPasswordRequestDto.java
  src/main/java/com/sscanner/team/user/requestdto/UserResetPasswordRequestDto.kt
  src/main/java/com/sscanner/team/user/responsedto/UserFindIdResponseDto.java
  src/main/java/com/sscanner/team/user/responsedto/UserFindIdResponseDto.kt
  src/main/java/com/sscanner/team/user/responsedto/UserMypageResponseDto.java
  src/main/java/com/sscanner/team/user/responsedto/UserMypageResponseDto.kt
  src/main/java/com/sscanner/team/user/responsedto/UserNicknameUpdateResponseDto.java
  src/main/java/com/sscanner/team/user/responsedto/UserNicknameUpdateResponseDto.kt
  src/main/java/com/sscanner/team/user/responsedto/UserPhoneUpdateResponseDto.java
  src/main/java/com/sscanner/team/user/responsedto/UserPhoneUpdateResponseDto.kt
  src/main/java/com/sscanner/team/user/scheduler/UserDeletionScheduler.java
  src/main/java/com/sscanner/team/user/scheduler/UserDeletionScheduler.kt
  src/main/java/com/sscanner/team/user/service/UserServiceImpl.kt
Labels: 지은, Migration

#23 Migration/6 board
  src/main/java/com/sscanner/team/admin/controller/AdminController.java
  src/main/java/com/sscanner/team/admin/controller/AdminController.kt
  src/main/java/com/sscanner/team/admin/requestdto/AdminBoardRequestDTO.java
  src/main/java/com/sscanner/team/admin/requestdto/AdminBoardRequestDTO.kt
  src/main/java/com/sscanner/team/admin/responsedto/AdminBoardInfoResponseDTO.java
  src/main/java/com/sscanner/team/admin/responsedto/AdminBoardInfoResponseDTO.kt
  src/main/java/com/sscanner/team/admin/responsedto/AdminBoardListResponseDTO.java
  src/main/java/com/sscanner/team/admin/responsedto/AdminBoardListResponseDTO.kt
  src/main/java/com/sscanner/team/admin/responsedto/AdminEctBoardResponseDTO.java
  src/main/java/com/sscanner/team/admin/responsedto/AdminEctBoardResponseDTO.kt
  src/main/java/com/sscanner/team/admin/responsedto/AdminModifyBoardResponseDTO.java
  src/main/java/com/sscanner/team/admin/responsedto/AdminModifyBoardResponseDTO.kt
  src/main/java/com/sscanner/team/admin/service/AdminService.java
  src/main/java/com/sscanner/team/admin/service/AdminService.kt
  src/main/java/com/sscanner/team/admin/service/AdminServiceImpl.java
  src/main/java/com/sscanner/team/admin/service/AdminServiceImpl.kt
  src/main/java/com/sscanner/team/board/controller/BoardController.java
  src/main/java/com/sscanner/team/board/controller/BoardController.kt
  src/main/java/com/sscanner/team/board/entity/Board.java
  src/main/java/com/sscanner/team/board/entity/Board.kt
  src/main/java/com/sscanner/team/board/entity/BoardImg.java
  src/main/java/com/sscanner/team/board/entity/BoardImg.kt
  src/main/java/com/sscanner/team/board/repository/BoardImgRepository.java
  src/main/java/com/sscanner/team/board/repository/BoardImgRepository.kt
  src/main/java/com/sscanner/team/board/repository/BoardRepository.java
  src/main/java/com/sscanner/team/board/repository/BoardRepository.kt
  src/main/java/com/sscanner/team/board/requestdto/BoardCreateRequestDTO.java
  src/main/java/com/sscanner/team/board/requestdto/BoardCreateRequestDTO.kt
  src/main/java/com/sscanner/team/board/requestdto/BoardUpdateRequestDTO.java
  src/main/java/com/sscanner/team/board/requestdto/BoardUpdateRequestDTO.kt
  src/main/java/com/sscanner/team/board/responsedto/BoardImgResponseDTO.java
  src/main/java/com/sscanner/team/board/responsedto/BoardImgResponseDTO.kt
  src/main/java/com/sscanner/team/board/responsedto/BoardInfoResponseDTO.java
  src/main/java/com/sscanner/team/board/responsedto/BoardInfoResponseDTO.kt
  src/main/java/com/sscanner/team/board/responsedto/BoardListResponseDTO.java
  src/main/java/com/sscanner/team/board/responsedto/BoardListResponseDTO.kt
  src/main/java/com/sscanner/team/board/responsedto/BoardLocationInfoResponseDTO.java
  src/main/java/com/sscanner/team/board/responsedto/BoardLocationInfoResponseDTO.kt
  src/main/java/com/sscanner/team/board/responsedto/BoardResponseDTO.java
  src/main/java/com/sscanner/team/board/responsedto/BoardResponseDTO.kt
  src/main/java/com/sscanner/team/board/service/BoardImgService.java
  src/main/java/com/sscanner/team/board/service/BoardImgService.kt
  src/main/java/com/sscanner/team/board/service/BoardImgServiceImpl.java
  src/main/java/com/sscanner/team/board/service/BoardImgServiceImpl.kt
  src/main/java/com/sscanner/team/board/service/BoardService.java
  src/main/java/com/sscanner/team/board/service/BoardService.kt
  src/main/java/com/sscanner/team/board/service/BoardServiceImpl.java
  src/main/java/com/sscanner/team/board/service/BoardServiceImpl.kt
  src/main/java/com/sscanner/team/board/type/ApprovalStatus.java
  src/main/java/com/sscanner/team/board/type/ApprovalStatus.kt
  src/main/java/com/sscanner/team/board/type/BoardCategory.java
  src/main/java/com/sscanner/team/board/type/BoardCategory.kt
Labels: Migration

#5 Migration/2 log
  src/main/java/com/sscanner/team/global/common/response/ApiResponse.java
  src/main/java/com/sscanner/team/global/common/response/ApiResponse.kt
  src/main/java/com/sscanner/team/global/configure/CustomHighlightConverter.java
  src/main/java/com/sscanner/team/global/configure/CustomHighlightConverter.kt
  src/main/java/com/sscanner/team/global/configure/aop/HttpLoggingAspect.java
  src/main/java/com/sscanner/team/global/configure/aop/HttpLoggingAspect.kt
  src/main/java/com/sscanner/team/global/configure/aop/ServiceLogAspect.java
  src/main/java/com/sscanner/team/global/configure/aop/ServiceLogAspect.kt
  src/main/java/com/sscanner/team/global/configure/aop/TimeTrace.java
  src/main/java/com/sscanner/team/global/configure/aop/TimeTraceAspect.java
  src/main/java/com/sscanner/team/global/exception/BadRequestException.java
  src/main/java/com/sscanner/team/global/exception/BadRequestException.kt
  src/main/java/com/sscanner/team/global/exception/DuplicateException.java
  src/main/java/com/sscanner/team/global/exception/DuplicateException.kt
  src/main/java/com/sscanner/team/global/exception/ExceptionCode.kt
Labels: 재희, Migration

#25 Migration/24 comment
  src/main/java/com/sscanner/team/comment/controller/CommentController.java
  src/main/java/com/sscanner/team/comment/controller/CommentController.kt
  src/main/java/com/sscanner/team/comment/entity/Comment.java
  src/main/java/com/sscanner/team/comment/entity/Comment.kt
  src/main/java/com/sscanner/team/comment/repository/CommentRepository.java
  src/main/java/com/sscanner/team/comment/repository/CommentRepository.kt
  src/main/java/com/sscanner/team/comment/requestdto/CommentCreateRequestDTO.java
  src/main/java/com/sscanner/team/comment/requestdto/CommentCreateRequestDTO.kt
  src/main/java/com/sscanner/team/comment/responsedto/CommentResponseDTO.java
  src/main/java/com/sscanner/team/comment/responsedto/CommentResponseDTO.kt
  src/main/java/com/sscanner/team/comment/service/CommentService.java
  src/main/java/com/sscanner/team/comment/service/CommentService.kt
  src/main/java/com/sscanner/team/comment/service/CommentServiceImpl.java
  src/main/java/com/sscanner/team/comment/service/CommentServiceImpl.kt
Labels: 훈일, Migration

#28 fix : 오류 수정
  src/main/java/com/sscanner/team/global/configure/SecurityConfig.kt
  src/main/java/com/sscanner/team/user/controller/UserController.kt
Labels: 지은

#29 Migration/26 prometheus 모니터링 추가
  .github/workflows/ci-cd.yml
  .github/workflows/ci.yml
  build.gradle.kts
  docker-compose/compose.blue.yml
  docker-compose/compose.green.yml
  src/main/java/com/sscanner/team/comment/controller/CommentController.kt
  src/main/java/com/sscanner/team/global/common/response/ApiResponse.kt
  src/main/java/com/sscanner/team/global/configure/SecurityConfig.kt
  src/main/java/com/sscanner/team/trashcan/controller/TrashcanApiController.kt
  src/main/resources/application.yml
Labels: 재희, Migration
